# Based on a build template from:
#
# https://docs.haskellstack.org/en/stable/travis_ci/

# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-generic-extra
      - texlive-latex-extra
      - texlive-luatex
      - texlive-science
      - texlive-xetex
      - latexmk
      - fonts-lmodern
      - fonts-texgyre

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- export IDDQD=1
- stack --no-terminal test --haddock --no-haddock-deps
# Generate PGF diagrams for the notes
- stack exec tex-plots
# Set publication date strings
- export PUB_DATE=$(date '+%Y-%m-%dT%H:%M:%S%z')
- sed -i -e "s/PUBDATE/${PUB_DATE}/" notes/notes.tex
- sed -i -e "s/{{PUB_DATE}}/${PUB_DATE}/" gh-pages/index.html
# Build the notes and GH Pages site
- pushd notes; make; popd
- cp notes/notes.pdf gh-pages/notes.pdf
- cp logo.svg gh-pages/logo.svg

# Deploy necessary components to GitHub Pages
deploy:
  provider: pages
  local_dir: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master