name:                space-workshop
version:             0.1.0.0
github:              "githubuser/space-workshop"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/space-workshop#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- Chart
- Chart-diagrams
- diagrams-lib
- diagrams-rasterific
- iterm-show
- JuicyPixels
- lens
- linear
- mtl
- primitive
- text
- transformers
- vector
- vector-algorithms
- vector-space

library:
  source-dirs: src

_ghc-options: &ghc-options
  - -O0
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-import-lists

executables:

  drag-plots:
    main:                Main.hs
    source-dirs:         app/drag-plots
    ghc-options:         *ghc-options
    dependencies:
    - space-workshop

tests:
  space-workshop-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:         *ghc-options
    dependencies:
    - space-workshop
    - doctest
    - hedgehog
    - tasty
    - tasty-hedgehog
