name:                space-workshop
version:             0.1.0.0
github:              "lancelet/space-workshop"
license:             BSD3
author:              "Jonathan Merritt and Luke Clifton"
maintainer:          "j.s.merritt@gmail.com.com"
copyright:           "2019 Jonathan Merritt and Luke Clifton"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            LambdaJam 2019 Spaceflight Workshop
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/space-workshop#readme>

build-tools:
- wshterm
- ghcid

dependencies:
- base >= 4.7 && < 5
- bytestring
- Chart
- Chart-diagrams
- colour
- diagrams-lib
- diagrams-pgf
- diagrams-rasterific
- iterm-show
- JuicyPixels
- lens
- linear
- MemoTrie
- text
- units
- units-defs
- vector
- vector-space

library:
  source-dirs: src

_ghc-options: &ghc-options
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-import-lists

executables:

  tex-plots:
    main:                Main.hs
    source-dirs:         app/tex-plots
    ghc-options:         *ghc-options
    dependencies:
    - space-workshop

tests:
  space-workshop-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:         *ghc-options
    dependencies:
    - space-workshop
    - doctest
    - hedgehog
    - tasty
    - tasty-hedgehog
