name:                haskell-orbital-launch
version:             0.1.0.0
github:              "lancelet/haskell-orbital-launch"
license:             BSD3
author:              "Jonathan Merritt and Luke Clifton"
maintainer:          "j.s.merritt@gmail.com"
copyright:           "2019 Jonathan Merritt and Luke Clifton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/launch-workshop#readme>

dependencies:
- base >= 4.7 && < 5
- Chart
- Chart-diagrams
- diagrams-core
- diagrams-lib
- diagrams-svg
- lens
- linear
- vector
- vector-sized

library:
  source-dirs: src

_ghc-options: &ghc-options
  - -O2
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-import-lists

executables:
  ode-examples:
    main:                Main.hs
    source-dirs:         app/ode-examples
    ghc-options:         *ghc-options
    dependencies:
    - haskell-orbital-launch

  lunar-ascent:
    main:                Main.hs
    source-dirs:         app/lunar-ascent
    ghc-options:         *ghc-options
    dependencies:
    - haskell-orbital-launch

tests:
  launch-workshop-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:         *ghc-options
    dependencies:
    - haskell-orbital-launch
