resolver: lts-14.4
packages:
- .
extra-deps:
- iterm-show-0.1.0.1
- diagrams-pgf-1.4.1
- posix-pty-0.2.1.1
- texrunner-0.0.1.2
- units-2.4.1.1
- units-defs-2.0.1.1
- units-parser-0.1.1.3
- wshterm-0.1.0.1

nix:
  pure: false
